### ISSUE TITLE
Implementar poderes ao heróis

### ISSUE THREAD

**Issue by gfariasilva** [Game-JAVA/Bytes-brilhantes#3]

**Comment by valentinaoliveira** [comment]
Faria - guerreiro
         PODER: invoca a "fúria do dragão", aumentando o dano dos ataques em 2x por 3 rodadas
         Tempo de recarga: 5 rodadas

Valentina- Necromancer 
         PODER: Ressucitar um aliado a cada 2 níveis

Bruno - Elementalista
        PODER: ataques elementais (fogo, agua, terra, ar)
        Habilidade especial: "tornado de fogo"
        Tempo de recarga: 2 rodadas

Letícia - Mage 
	Poder: Atordoa seus inimigos em uma prisão mágica, fazendo com que ele fique 2 rodadas sem jogar
